### ISSUE TITLE
Jar file are shown as application/jar instead of application/java-archive

### ISSUE THREAD

**Issue by eplaut** [dveselov/python-libmagic#1]
```
$ grep jar /etc/mime.types
application/java-archive			jar

In [4]: magic.from_file('/usr/share/java/unoloader.jar', mime=True)
Out[4]: 'application/jar'
```

`application/jar` is unknown mime type (python builtin `mimetypes` uses the `/etc/mime.types` file)

Thanks,
Eli

**Comment by dveselov** [comment]
Hi! Sorry for delay.
libmagic uses own mimetype database (by default `/usr/share/misc/magic.mgc`)
You can get more info at [manpage](http://linux.die.net/man/3/libmagic).
